@startuml car
skinparam ClassAttributeIconSize 0
class Car{
    + Color
    - Model
    - licenseNumber
    moveForward()
    moveBackward()
    stop()
    turnRight()
    turnLeft()
}

class Engine{
    - capacity
    start()
    break()
}

class Stereo{
    -Speaker
    -VolumeLevel
    +VolumeUp()
    +VolumeDown()
    +Play()
    +Pause()
}

class Door{
    + Color
    + Glass
    + OpenGlass()
    + CloseGlass()
}

class Pistons{
    - Four-stroke engine
    - Intake()
    - Compression()
    - Combustion()
    - Exhaust()
}

class SparkPlugs{
    - Heat Range
    + Ignition()
}

class Radio{
    - Demodulation
    + ChangeFrequency()
}

class Cassette{
    - ReadableCassette
    + ReadCassette()
}

class Handle{
    + Color
    + Lock()
    + Unlock()
    + OpenDoor()
    + CloseDoor()
}

class Tuner{
    - ReceivableFrequency
    + receiveSelectedFrequency()
}

Car o-- Engine
Car o-- Stereo
Car o-- Door

Engine o-- Pistons
Engine o-- SparkPlugs

Stereo o-- Radio
Stereo o-- Cassette

Door o-- Handle

Radio o-- Tuner

@enduml

